version: '3.7'

services:
  elasticsearch:
    container_name: elasticsearch
    image: 'elasticsearch:7.4.2'
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: 'single-node'
  kibana:
    container_name: kibana
    image: 'kibana:7.4.2'
    ports:
      - 5601:5601

networks:
  default:
    external:
      name: elk

